#!/bin/sh

ASK=/usr/lib/ssh/x11-ssh-askpass
if [ ! -x $ASK ];then
	ASK=/usr/lib64/ssh/x11-ssh-askpass
fi
if [ -x ./qbiff ];then
	$ASK | ./qbiff -geometry +0-1 $@
else
	$ASK | qbiff -geometry +0-1 $@
fi
